name_model = "150M"
project = "debug_150m_zero_band"
run_id = "2c774d7c830b49e7855f4f9be6ea4d09"

[metric_logger]
type = "dummy"
base_url = "https://protocol-api.primeintellect.ai"

[train]
micro_bs = 16 # change this base on the gpu
sharding_strategy = "SHARD_GRAD_OP"

[optim]
batch_size = 512
warmup_steps = 1000
total_steps = 88_000
lr = 4e-4
