name_model = "150M"
project = "debug_150m_zero_band"

[metric_logger]
type = "dummy"

[train]
micro_bs = 16 # change this base on the gpu
sharding_strategy = "SHARD_GRAD_OP"

[optim]
batch_size = 512
warmup_steps = 1000
total_steps = 88_000
lr = 4e-4
