name_model = "debugmodel"
project = "/tmp/debug"

[metric_logger]
type = "dummy"

[train]
micro_bs = 8
sharding_strategy = "FULL_SHARD"

[optim]
batch_size = 16
warmup_steps = 10
total_steps = 4

[data]
fake = true

[diloco]
inner_steps = 2

