name_model = "debugmodel"
project = "debug"

[train]
micro_bs = 8
sharding_strategy = "FULL_SHARD"

[optim]
batch_size = 16
warmup_steps = 10
total_steps = 5000

[data]
fake_data = true

[diloco]
inner_steps = 10