name_model = "debugmodel"
project = "/tmp/debug"

[monitor]
type = "dummy"

[train]
micro_bs = 8
sharding_strategy = "SHARD_GRAD_OP"

[optim]
batch_size = 16
warmup_steps = 10
total_steps = 4

[data]
fake = true

